name = "CosmoTools"
uuid = "fab82211-602b-461d-8fab-2b676713216d"
authors = ["Gaétan Facchinetti"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
